# Generated by Django 6.0.7 on 2026-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_category_options_remove_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
